title: "Rodrigue Rizk"
description: "Personal and research website"
baseurl: "" # leave empty for root
url: "https://rodriguerizk.github.io"
markdown: kramdown
#theme: minima # You can remove this if you want to fully use your own HTML

