title: "Rodrigue Rizk"
description: "Homepage of Dr. Rodrigue Rizk. Research in AI, deep learning, reinforcement learning, cognitive modeling, autonomous learning systems, and quantum computing."
highlighter: rouge
baseurl: "" # leave empty for root
url: "https://rodriguerizk.github.io"
markdown: kramdown
#theme: minima # You can remove this if you want to fully use your own HTML

# Required for pagination
plugins:
  - jekyll-paginate
  - jekyll-reading-time
  - jekyll-feed

  
paginate: 10               # number of posts per page
paginate_path: "/blog/page:num/"





